version: '3.4'
services: 
  mysqldb: 
    image: mysql:8.0.26
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_stecnology
    expose:
      - 3306
    ports: 
      - 3306:3306
    networks:
      - stec-network
      
  stecnology-api: 
    image: dockersam123/stecnology-api
    restart: always
    build: ../../stecnology-api
    working_dir: /stecnology-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - mysqldb
    depends_on:
      - mysqldb
    networks:
      - stec-network  
networks:
  stec-network:
        driver: bridge