version: '3.4'
services:
  mysqldb:
    image: mysql:8.0.26
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    enviroment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db_stecnology
    ports:
      - "3306:3306"
    networks:
      - stecnology-network
  stecnology-api:
    image: stecnology-API
    restart: always
    build: ./stecnology-api
    working_dir: /stecnology-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    comand: mvn clean spring-boot:run
    links:
      - mysqldb
    depends_on:
      - mysqldb
    networks:
      - stecnology-network
networks: 
    stecnology-network:
        driver: bridge
