version: '3.4'
services: 
  mysqldb: 
    image: mysql:8.0.26
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db_stecnology
    ports: 
      - 3306:3306
    networks:
      - stec-network
  
  stecnology-api: 
    image: stecnology-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - mysqldb
    depends_on:
      - mysqldb
    networks:
      - stec-network
      
networks:
  stec-network:  